### ISSUE TITLE
image files can not end with a dash

### ISSUE THREAD

**Issue by drkgreyhawk** [dillonkearns/elm-pages#155]
We had an issue come up involving images that have a name ending with a dash, for example `dan-meyers-hluojzjlvxc-unsplash-1-.jpg`. Our client uploaded an image with the example name and elm failed to compile. Upon removing the final dash in the filename elm was able to compile.

```
-- PROBLEM IN RECORD ------------------------------------------------- Pages.elm
9:30:34 AM: I am partway through parsing a record, but I got stuck here:
9:30:34 AM: 94|         { danMeyers = (buildImage [ "article-covers", "dan-meyers.jpg" ] { width = 1732, height = 1154 })
9:30:34 AM: 95|         , danMeyersHluojzjlvxcUnsplash1- = (buildImage [ "article-covers", "dan-meyers-hluojzjlvxc-unsplash-1-.jpg" ] { width = 640, height = 427 })
9:30:34 AM:                                            ^
9:30:34 AM: I just saw a field name, so I was expecting to see an equals sign next. So try
9:30:34 AM: putting an = sign here?
9:30:34 AM: Note: If you are trying to define a record across multiple lines, I recommend
9:30:34 AM: using this format:
9:30:34 AM:     { name = "Alice"
9:30:34 AM:     , age = 42
9:30:34 AM:     , height = 1.75
9:30:34 AM:     }
9:30:34 AM: Notice that each line starts with some indentation. Usually two or four spaces.
9:30:34 AM: This is the stylistic convention in the Elm ecosystem.
9:30:34 AM: Detected problems in 1 module.
9:30:34 AM: ReferenceError: Elm is not defined
9:30:34 AM:     at /opt/build/repo/node_modules/elm-pages/generator/src/compile-elm.js:17:19
9:30:34 AM:     at /opt/build/repo/node_modules/elm-pages/generator/src/compile-elm.js:34:7
9:30:34 AM:     at new Promise (<anonymous>)
9:30:34 AM:     at runElm (/opt/build/repo/node_modules/elm-pages/generator/src/compile-elm.js:6:10)
9:30:34 AM:     at run (/opt/build/repo/node_modules/elm-pages/generator/src/generate-elm-stuff.js:58:10)
9:30:34 AM:     at /opt/build/repo/node_modules/elm-pages/generator/src/elm-pages.js:86:7
```

**Comment by carlfredrikhero** [comment]
This is due to the fact that filenames are saved as keys in an Elm record. Image file has to begin with a lower case letter, Uppercase letters and numbers makes the build fail.

**Comment by dillonkearns** [comment]
Similar to https://github.com/dillonkearns/elm-pages/issues/21#issuecomment-890443533, this issue won't happen going forward because the `Pages.images` record is no longer generated. See that comment for the reasoning behind that and new direction. Thanks all for reporting the issue!
