### ISSUE TITLE
Build always tries to launch chrome

### ISSUE THREAD

**Issue by Aarkon** [dillonkearns/elm-pages#193]
Hi!

It is entirely possible I'm missing something here, but I just can't figure out how to properly build a page even with the naked quick starter repo. Starting the dev server is no problem at all, but building really is an issue. `npm run build` does a whole lot of compilation work, but then suddenly tries to launch chrome (what I certainly don't want since I compile on a headless server in a pipeline):

```
[Favicons] Images:composite: Compositing favicon on 180x180 canvas with offset 0...
98% after emittingError: Failed to launch chrome!
/home/jakob/src/elm-pages-starter/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/jakob/src/elm-pages-starter/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/home/jakob/src/elm-pages-starter/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
(node:350019) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at PuppeteerRenderer.destroy (/home/jakob/src/elm-pages-starter/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:140:21)
    at Prerenderer.destroy (/home/jakob/src/elm-pages-starter/node_modules/@prerenderer/prerenderer/es6/index.js:87:20)
    at PrerendererInstance.initialize.then.then.then.then.then.then.then.then.catch.err (/home/jakob/src/elm-pages-starter/node_modules/prerender-spa-plugin/es6/index.js:144:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:350019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:350019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried this on more than one linux system, it't the same everywhere. I have to CTRL + C out of the process and sometimes I am even left without a `dist` folder. Even worse, it completely stalls every pipeline, which I then have to stop manually which means the artifacts will never be deployed.

Again, I'm not sure if I'm using the tool right, but I haven't found any documentation about building and deploying.
Thanks for the great work so far non the less! 😄

**Comment by Aarkon** [comment]
Closing this because I fell victim to a misunderstanding what Chrome does in the build and how it can be solved.
Long story short: Make sure you have the dependencies for headless chrome available.
