### ISSUE TITLE
Brand new installation, murmur3 corrupt

### ISSUE THREAD

**Issue by Erudition** [dillonkearns/elm-pages#266]
Couldn't find any issue in this repo about this already, but when murmur3 went through a name change, this issue affected all dependents: 
https://github.com/robinheghan/murmur3/issues/5

So a brand new experience, following the docs, results in an error right off the bat:

```console
pop-os:~/Projects$ npx elm-pages init snowdrift-elm-site
```
```console
Need to install the following packages:
  elm-pages
Ok to proceed? (y) y
Creating snowdrift-elm-site project...
Project is successfully created in `/home/connor/Projects/snowdrift-elm-site`.
```
```console
pop-os:~/Projects$ cd snowdrift-elm-site/
pop-os:~/Projects/snowdrift-elm-site$ npm install
```
```console
> postinstall
> elm-tooling install

/home/Projects/snowdrift-elm-site/elm-tooling.json
elm 0.19.1 link created: node_modules/.bin/elm -> /home/.elm/elm-tooling/elm/0.19.1/elm
    To run: npx elm
elm-format 0.8.5 link created: node_modules/.bin/elm-format -> /home/.elm/elm-tooling/elm-format/0.8.5/elm-format
    To run: npx elm-format

added 300 packages, and audited 301 packages in 16s

31 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```console
pop-os:~/Projects/snowdrift-elm-site$ npm start
```
```console
> start
> elm-pages dev

elm-pages dev server running at <http://localhost:1234>
Unexpected error TypeError: Cannot read property 'some' of undefined
    at handleNavigationRequest (/home/Projects/snowdrift-elm-site/node_modules/elm-pages/generator/src/dev-server.js:311:59)
-- CORRUPT PACKAGE DATA --------------- 
I downloaded the source code for robinheghan/murmur3 1.0.0 from:

    https://github.com/robinheghan/murmur3/zipball/1.0.0/

But it looks like the hash of the archive has changed since publication:

  Expected: cc300658d490f65ed3253a9909a938329da9ed71
    Actual: 90ab27937cdda33a3c144b153677ebcfbdb62324

This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
well.
Ran in 59ms  /
Ran in 4ms   /index.js
Ran in 2ms   /style.css
Ran in 2ms   /hmr.js
Ran in 0ms   /elm.js
Unexpected error TypeError: Cannot read property 'some' of undefined
    at handleNavigationRequest (/home/Projects/snowdrift-elm-site/node_modules/elm-pages/generator/src/dev-server.js:311:59)
-- CORRUPT PACKAGE DATA --------------- 
I downloaded the source code for robinheghan/murmur3 1.0.0 from:

    https://github.com/robinheghan/murmur3/zipball/1.0.0/

But it looks like the hash of the archive has changed since publication:

  Expected: cc300658d490f65ed3253a9909a938329da9ed71
    Actual: 90ab27937cdda33a3c144b153677ebcfbdb62324

This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
well.
Ran in 2ms   /content.json
```

**Comment by dillonkearns** [comment]
`robinheghan/murmur3` is the renamed package, so that's the correct name.

The corrupt package data error you're getting is related to an incident today where GitHub released a change that resulted in different checksums. There's a discussion of it here: https://discourse.elm-lang.org/t/potential-breaking-change-in-github-zipballs-codec/8121

So this isn't an elm-pages specific issue but a general incident that can effect any Elm installation process (depending on whether you hit the GitHub servers where the feature flag was rolled out or not, and whether you have dependencies cached in your `ELM_HOME`, so the error will come and go depending on those conditions).

I'll close this issue here since it's not related to elm-pages and is being tracked elsewhere (the #core-coordination channel in the Elm slack is the best place to follow the details, but short answer is GitHub is resolving this issue and you should see these types of errors going away soon).

Additional reference:

https://twitter.com/tgummerer/status/1488493440103030787

https://twitter.com/tgummerer/status/1488566292265250820
