### ISSUE TITLE
Unable to start examples

### ISSUE THREAD

**Issue by shahnhogan** [dillonkearns/elm-pages#395]
First -- `elm-pages` is awesome! Thank you!

I'm starting to work my way through the examples in `elm-pages`, however, I ran into an issue starting `examples\end-to-end`. I cloned the repo and from the repo root folder, I ran `npm run start`, which should start up the `end-to-end` example. However, I'm getting the error below. I've tried both nodejs 18.16.0 and 19.9.0 with the examples `end-to-end`, `base-path`, and `hackernews` with no luck and the same error. 

```bash
npm run start

> elm-pages@3.0.6 start
> cd examples/end-to-end && npm i && npx elm-pages dev


added 198 packages, and audited 200 packages in 2s

36 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (5 moderate, 4 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/shahnhogan/Developer/explorations/dillonkearns/elm-pages/codegen/elm-pages-codegen.cjs' imported from /Users/shahnhogan/Developer/explorations/dillonkearns/elm-pages/generator/src/generate-template-module-connector.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:231:11)
    at moduleResolve (node:internal/modules/esm/resolve:850:10)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/hooks:654:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:309:30)
    at ESMLoader.resolve (node:internal/modules/esm/loader:312:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/esm/translators:107:35) {
  code: 'ERR_MODULE_NOT_FOUND'
}
file:///Users/shahnhogan/Developer/explorations/dillonkearns/elm-pages/generator/src/dev-server.js:40
    if (!messages[0]?.startsWith("Failed to load url")) {
                      ^

TypeError: messages[0]?.startsWith is not a function
    at console.error (file:///Users/shahnhogan/Developer/explorations/dillonkearns/elm-pages/generator/src/dev-server.js:40:23)
    at process.<anonymous> (file:///Users/shahnhogan/Developer/explorations/dillonkearns/elm-pages/generator/src/render.js:18:11)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v19.9.0
```

**Comment by tanyabouman** [comment]
I had the same problem and solved it with:

```
git submodule init
git submodule update
rm -rf examples/end-to-end/node_modules
```

**Comment by dillonkearns** [comment]
Sounds like this is resolved, I'll mark as closed. Thanks!
