### ISSUE TITLE
`Debug.todo` causes a `Script` to stop with no error message

### ISSUE THREAD

**Issue by miniBill** [dillonkearns/elm-pages#462]
A `Debug.todo` inside a `BackendTask.andThen` causes the script to stop running with no error message and a zero exit code

**Comment by dillonkearns** [comment]
Great point! That should definitely give a non-zero exit status and print the error message.

**Comment by dillonkearns** [comment]
I'm not able to reproduce it on master:

```elm
module Todo exposing (run)

import BackendTask
import Pages.Script as Script exposing (Script)


run : Script
run =
    Script.withoutCliOptions
        (BackendTask.succeed ()
            |> BackendTask.andThen
                (\_ ->
                    Debug.todo "!!!TODO!!!!"
                )
        )

```

**Comment by dillonkearns** [comment]
```shell
npx elm-pages run script/src/Todo.elm
Trace: Error: TODO in module `Todo` on line 13

!!!TODO!!!!
    at _Debug_crash (/Users/dillonkearns/src/github.com/dillonkearns/elm-pages/examples/end-to-end/script/elm-stuff/elm-pages/elm.cjs:498:10)
    at /Users/dillonkearns/src/github.com/dillonkearns/elm-pages/examples/end-to-end/script/elm-stuff/elm-pages/elm.cjs:254:3
    at /Users/dillonkearns/src/github.com/dillonkearns/elm-pages/examples/end-to-end/script/elm-stuff/elm-pages/elm.cjs:9176:7
    at Function.f (/Users/dillonkearns/src/github.com/dillonkearns/elm-pages/examples/end-to-end/script/elm-stuff/elm-pages/elm.cjs:9085:13)
    at A2 (/Users/dillonkearns/src/github.com/dillonkearns/elm-pages/examples/end-to-end/script/elm-stuff/elm-pages/elm.cjs:56:28)
    at /Users/dillonkearns/src/github.com/dillonkearns/elm-pages/examples/end-to-end/script/elm-stuff/elm-pages/elm.cjs:9168:2
    at Object.<anonymous> (/Users/dillonkearns/src/github.com/dillonkearns/elm-pages/examples/end-to-end/script/elm-stuff/elm-pages/elm.cjs:9306:5)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Command.<anonymous> (file:///Users/dillonkearns/src/github.com/dillonkearns/elm-pages/generator/src/cli.js:168:17)
Trace: Unexpected error format Unexpected error {}
    at restoreColor (file:///Users/dillonkearns/src/github.com/dillonkearns/elm-pages/generator/src/error-formatter.js:104:13)
    at restoreColorSafe (file:///Users/dillonkearns/src/github.com/dillonkearns/elm-pages/generator/src/error-formatter.js:121:14)
    at Command.<anonymous> (file:///Users/dillonkearns/src/github.com/dillonkearns/elm-pages/generator/src/cli.js:169:21)
Error: TODO in module `Todo` on line 13

!!!TODO!!!!
```

**Comment by dillonkearns** [comment]
Exits with code 1.

**Comment by miniBill** [comment]
Got it!
```elm
module Repro exposing (run)

import BackendTask
import Pages.Script as Script exposing (Script)


run : Script
run =
    Script.log "Just"
        |> BackendTask.andThen (\_ -> Debug.todo "break")
        |> Script.withoutCliOptions
```
